DROP TABLE IF EXISTS delegations;

CREATE TABLE IF NOT EXISTS delegations (
    id SERIAL PRIMARY KEY,
    validator_address VARCHAR(255) NOT NULL REFERENCES validators(address) ON DELETE CASCADE,
    delegator_address VARCHAR(255) NOT NULL,
    delegation_shares VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 