CREATE TABLE IF NOT EXISTS validators (
    address VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    enabled_tracking BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 